thinkjs/thinkjs

lib/Conf/tag.js, lib/Lib/Core/App.js
=> 添加可以对错误的自定义处理

lib/Lib/Driver/Db/MongoDb.js
=> '修复出现OverwriteModelError'

README.md
=> 英文版文档指向英文官网

bin/index.js, template/nginx_ssl_http2.conf
=> add nginx conf with https

bin/index.js, template/nginx_ssl_http2.conf
在项目模板里增加http2的nginx配置，需要nginx版本1.9.5以上使用
=> add nginx config with https

src/adapter/cache/memcache.js, src/adapter/cache/redis.js
=> cache adapter的bug修复

src/adapter/cache/memcache.js, src/adapter/cache/redis.js
=> 修复memcache、redis的cache adapter的bug;

src/model/base.js
await model.update(data);
data 包含 id 的时候应该能够影响关联表，但之前不行，因为 id 被误删了
=> 修复update的时候因为误删了id字段导致不能关联更新的bug

src/adapter/websocket/socket.io.js
fixed multi socket and  namespace
=> fixed multi connect and  namespace

src/model/base.js, test/model/base.js
解决了countSelect在PostgreSQL上面不能使用order的问题。
=> add order support for 'countSelect' on postgresql

src/model/relation.js, test/model/relation.js
=> Quick fix #417

src/adapter/db/postgresql.js
Fixed #450 and added ILIKE, NOT ILIKE, BETWEEN and NOT BETWEEN where conditions for postgres.
=> PostgreSql - Added case sensitive table and field names and some conditions

src/adapter/db/postgresql.js
Added a conditional statement to only add quotes to key that don't already have them.
=> Fixed issue 459

src/adapter/db/postgresql.js, test/adapter/db/postgresql.js
Workaround PostgreSQL testcase and fix #459
=> PostgreSQL testcase + fixes for #459

appveyor.yml, src/adapter/db/postgresql.js, test/adapter/db/postgresql.js, test/adapter/db/sqlite.js, test/adapter/session/db.js, test/adapter/socket/mysql.js, test/core/http.js, test/core/view.js, test/logic/base.js, test/model/_base.js, test/util/watch_compile.js
@welefen i'm fix issue #459 , create testcase for parseGroup and small work around `group by`
PS: 2nd commit fix troubles for eslint
=> fixes for #461 + testcases + fix troubles with AppVeyor

src/adapter/db/postgresql.js, test/adapter/db/postgresql.js, test/core/think.js, test/model/_base.js, test/model/base.js, test/model/mongo.js, test/model/relation.js, test/service/base.js
fix issues #472 and #470 (https://github.com/75team/thinkjs/pull/470#issuecomment-253413398 broken test cases)
=> fix #470 #472 issues, fixed test cases

template/www/README.md
file www/index.js is not found.
=> fixed template readme

.idea/watcherTasks.xml, src/model/base.js, test/model/base.js
之前优化写法的时候，把flag=true的默认值改成false，忘记把find和select方法里面的参数改成true了。
=> 把find和select方法里面的参数改成true

src/middleware/parse_route.js
cleanPathname function in parse_route.js can replace with a regular expression
=> Optimize parse_route.js

README.md, README_zh-CN.md
=> 修改文档:创建项目默认为es6，不需要--es

template/config/error.es, template/config/error.js, template/config/error.ts
Strings must use singlequote —— by eslint rules.
=> fix template's string quotes

src/adapter/db/_parse_mongo.js
当value是objectId类型的时候，也同样将value转换成objectId
=> 优化mongodb的where方法

index.d.ts
this.post(name) should return some post values, it cloud be string, int, or object, so it return value type should be any.
=> [bugfix] this.post('id') ts warning

index.d.ts
补充缺少的rules属性类型验证
https://thinkjs.org/zh-cn/doc/3.0/logic.html
=> 补充缺少的rules属性类型验证

index.d.ts, lib/application.js, lib/loader.js
```js
const app = new Application({
RUNTIME_PATH: path.join(__dirname, 'runtime'),
});
```
=> [feature] expose RUNTIME_PATH config

src/adapter/socket/redis.js, src/config/redis.js, src/config/session.js, src/core/think.js
add ioredis and session prefix for redis cluster.
=> Pr ioredis

package.json
Support "none" in sameSite option.
=> Upgrade cookies to 0.8.0

package.json
=> fixbug: 解决上传文件获取文件列表为空列表的问题。

src/util/cookie.js, test/util/cookie.js
类似
https://github.com/thinkjs/thinkjs/pull/1504
使2.x  cookie 支持  samesite
=> [feature] cookie support the samesite option
